name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run simplecompile.sh
      run: chmod 755 simplecompile.sh; ./simplecompile.sh
